### ISSUE TITLE
Compile error with weston-git

### ISSUE THREAD

**Issue by yan12125** [giucam/orbital#46]
```
[ 76%] Building CXX object src/compositor/drm-backend/CMakeFiles/drm-backend.dir/drm-backend.cpp.o
/home/yen/Projects/tmp/orbital/src/compositor/drm-backend/drm-backend.cpp: In member function ‘virtual bool Orbital::DrmBackend::init(weston_compositor*)’:
/home/yen/Projects/tmp/orbital/src/compositor/drm-backend/drm-backend.cpp:84:12: error: ‘struct weston_drm_backend_config’ has no member named ‘use_current_mode’
     config.use_current_mode = false;
            ^~~~~~~~~~~~~~~~
```
This field is moved to another struct in https://github.com/wayland-project/weston/commit/605ac8e685b24c0a88a86f6d64d0fb36ccd26270

**Comment by n3rdopolis** [comment]
Can Orbital be updated Since Weston 2.0 is released?

**Comment by je-vv** [comment]
I'm also wondering...

Furthermore, is development sort of stalled?  Seems like there haven't been any commit since 2016...

**Comment by yan12125** [comment]
There are some other Qt-based wayland compositor: http://phoronix.com/scan.php?page=news_item&px=Wayland-Compositors-Less-2017. I didn't try one by one but lots of them look interesting :)

**Comment by giucam** [comment]
It now builds with weston 2.0.

**Comment by giucam** [comment]
ANd it also builds with weston git.

**Comment by ibrokemypie** [comment]
Hey, seems to have broken with weston-git again, I think weston-git builds as libweston-3 now instead of 2, so orbital wont build for me.

**Comment by giucam** [comment]
It builds now.
